# Generated by Django 5.0.1 on 2026-10-10 11:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Weekend feast: 15% off pickup"', max_length=120)),
                ('description', models.CharField(blank=True, help_text='One or two short sentences shown under the title.', max_length=300)),
                ('badge', models.CharField(blank=True, help_text='Short label, e.g. "15% OFF". Generated if left blank.', max_length=30)),
                ('image', models.ImageField(blank=True, help_text='Optional background photo for the home page banner.', upload_to='promotions/')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off'), ('none', 'No discount (announcement only)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (e.g. 15) or dollar amount (e.g. 10.00).', max_digits=8)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum food subtotal for the discount to apply (0 = no minimum).', max_digits=8)),
                ('applies_to', models.CharField(choices=[('all', 'Pickup orders and reservation pre-orders'), ('pickup', 'Pickup orders only'), ('preorder', 'Reservation pre-orders only')], default='all', max_length=10)),
                ('starts_at', models.DateTimeField(help_text='When the promotion goes live (restaurant time).')),
                ('ends_at', models.DateTimeField(help_text='When it expires (restaurant time).')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to pause it without changing dates.')),
                ('show_on_home', models.BooleanField(default=True)),
                ('show_on_checkout', models.BooleanField(default=True)),
                ('cta_label', models.CharField(default='Order now', max_length=40)),
                ('cta_url', models.CharField(default='/menu', max_length=200)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher shows first when several are live.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'ends_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promotion'),
        ),
    ]
