# Generated by Django 5.0.1 on 2026-10-09 11:44

import django.db.models.deletion
import django.utils.timezone
import reservations.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['sort_order', '-is_flagship', 'name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='branch',
            name='booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='booking_interval_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(default='NZD', max_length=3),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_booking_duration_minutes',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='branch',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='deposit_policy',
            field=models.CharField(choices=[('none', 'No Deposit'), ('fixed', 'Fixed Per Booking'), ('per_guest', 'Per Guest')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='max_advance_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='max_online_party_size',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='branch',
            name='min_advance_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='branch',
            name='online_capacity',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='Pacific/Auckland', max_length=64),
        ),
        migrations.AddField(
            model_name='reservation',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='branch_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.branch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='reservation',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reservation',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='not_required', max_length=24),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('mobile', 'Mobile App'), ('admin', 'Dashboard'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('partner', 'Partner Channel')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('waiting', 'Waiting in Bar'), ('table_ready', 'Table Ready'), ('seated', 'Seated'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to=reservations.models.menu_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for a group-wide menu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='reservations.branch')),
            ],
            options={
                'ordering': ['-effective_from', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=20)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('refund', 'Refund')], default='deposit', max_length=20)),
                ('status', models.CharField(choices=[('requires_payment', 'Requires Payment'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='requires_payment', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NZD', max_length=3)),
                ('external_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('external_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('min_capacity', models.PositiveSmallIntegerField(default=1)),
                ('max_capacity', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservations.branch')),
            ],
            options={
                'ordering': ['branch', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='reservations.restauranttable'),
        ),
        migrations.AddConstraint(
            model_name='menudocument',
            constraint=models.UniqueConstraint(fields=('branch', 'version'), name='unique_menu_version_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_table_name_per_branch'),
        ),
    ]
