# Generated by Django 5.0.1 on 2026-10-09 18:32

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_backfill_guests_and_seed_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=reservations.models.default_payment_methods, help_text='Any of: card, cash, cash_on_pickup, cash_on_delivery. Card also needs a deposit policy and Stripe keys.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card (online deposit)'), ('cash', 'Cash at restaurant'), ('cash_on_pickup', 'Cash on pickup'), ('cash_on_delivery', 'Cash on delivery')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('pay_on_site', 'Pay on Site (cash)')], default='not_required', max_length=24),
        ),
    ]
