# Generated by Django 5.0.1 on 2026-10-10 10:23

from decimal import Decimal
from django.db import migrations, models


def cash_bookings_to_card(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')
    Reservation.objects.exclude(payment_method='card').update(payment_method='card')
    Reservation.objects.filter(payment_status='pay_on_site').update(payment_status='not_required')



class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_payment_methods'),
    ]

    operations = [
        migrations.RunPython(cash_bookings_to_card, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='branch',
            name='accepted_payment_methods',
        ),
        migrations.AlterField(
            model_name='branch',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount per booking (Fixed) or per guest (Per Guest), in the branch currency.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='deposit_policy',
            field=models.CharField(choices=[('none', 'No Deposit'), ('fixed', 'Fixed Per Booking'), ('per_guest', 'Per Guest')], default='none', help_text='Card deposit taken online via Stripe when booking. "No Deposit" = booking needs no payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card (online deposit)')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='not_required', max_length=24),
        ),
    ]
