# Generated by Django 5.0.1 on 2026-10-10 10:49

from django.db import migrations, models
from django.db.models import Q


def flag_addon_categories(apps, schema_editor):
    MenuCategory = apps.get_model('reservations', 'MenuCategory')
    MenuCategory.objects.filter(
        Q(slug__icontains='side') | Q(slug__icontains='drink') | Q(slug__icontains='beverage')
        | Q(slug__icontains='bread') | Q(slug__icontains='dessert')
    ).update(suggest_at_checkout=True)



class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_card_only_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pickup_enabled',
            field=models.BooleanField(default=True, help_text='Accept online pickup orders for this branch.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='pickup_prep_minutes',
            field=models.PositiveSmallIntegerField(default=25, help_text='Typical minutes until an ASAP pickup order is ready.'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='suggest_at_checkout',
            field=models.BooleanField(default=False, help_text='Suggest items from this category in the cart as add-ons (e.g. breads, drinks).'),
        ),
        migrations.RunPython(flag_addon_categories, migrations.RunPython.noop),
    ]
